name: Building BDF fonts

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v4
     
    - name: install font toolsmake bfs binary
      run:  |
        sudo apt install otf2bdf xfonts-utils wget
      
    - name: download fonts
      run: |
        mkdir bdf-fonts
        cd bdf-fonts
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/anonymous-pro/anonymous-pro.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/anonymous-pro/anonymous-pro-bold.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/anonymous-pro/license.txt -O anonymous-pro-license.txt
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/bront-dejavu/bront-dejavu.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/bront-dejavu/LICENSE.txt -O bront-dejavu-license.txt
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/bront-ubuntu/bront-ubuntu.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/bront-ubuntu/LICENSE.txt -O bront-ubuntu-license.txt
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/courier-prime/courier-prime.ttf 
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/courier-prime/courier-prime-bold.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/courier-prime/LICENSE.txt -O courier-prime-license.txt
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/chivo/chivo.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/chivo/chivo-bold.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/chivo/OFL.txt -O chivo-license.txt
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/inconsolata-go/inconsolata-go.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/inconsolata-go/inconsolata-go-bold.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/inconsolata-go/license.txt -O inconsolata-go-license.txt
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/julia-mono/julia-mono-bold.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/julia-mono/julia-mono.ttf        
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/julia-mono/LICENSE -O julia-mono-license.txt
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/terminus/terminus-bold.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/terminus/terminus.ttf        
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/terminus/license.txt -O terminus-license.txt
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/ubuntu/ubuntu-bold.ttf
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/ubuntu/ubuntu.ttf        
        wget https://github.com/braver/programmingfonts/raw/gh-pages/fonts/resources/ubuntu/license.txt -O ubuntu-license.txt
        cd ..
        ls
        pwd
    - name: creating bdf files
      run: |  
        pwd
        cd bdf-fonts
        ls ../fonts
        bash ../fonts/ttf2bdf.sh "anonymous pro" anonymous-pro.ttf "anonymous-pro-medium"
        bash ../fonts/ttf2bdf.sh "anonymous pro" anonymous-pro-bold.ttf "anonymous-pro-bold"
        bash ../fonts/ttf2bdf.sh "bront dejavu"  bront-dejavu.ttf "bront-dejavu-medium"
        bash ../fonts/ttf2bdf.sh "bront ubuntu"  bront-ubuntu.ttf "bront-ubuntu-medium"
        bash ../fonts/ttf2bdf.sh "chivo mono" chivo.ttf "chivo-mono-medium"
        bash ../fonts/ttf2bdf.sh "chivo mono" chivo-bold.ttf "chivo-mono-bold"
        bash ../fonts/ttf2bdf.sh "courier prime" courier-prime.ttf "courier-prime-medium"
        bash ../fonts/ttf2bdf.sh "courier prime" courier-prime-bold.ttf "courier-prime-bold"
        bash ../fonts/ttf2bdf.sh "inconsolata go" inconsolata-go.ttf "inconsolata-go-medium"
        bash ../fonts/ttf2bdf.sh "inconsolata go" inconsolata-go-bold.ttf "inconsolata-go-bold"
        bash ../fonts/ttf2bdf.sh "julia mono" julia-mono.ttf "julia-mono-medium"
        bash ../fonts/ttf2bdf.sh "julia mono" julia-mono-bold.ttf "julia-mono-bold"
        bash ../fonts/ttf2bdf.sh "terminus" terminus.ttf "terminus-medium"
        bash ../fonts/ttf2bdf.sh "terminus" terminus-bold.ttf "terminus-bold"
        bash ../fonts/ttf2bdf.sh "ubuntu mono" ubuntu.ttf "ubuntu-mono-medium"
        bash ../fonts/ttf2bdf.sh "ubuntu mono" ubuntu-bold.ttf "ubuntu-mono-bold"
        cd ..
    - name: Upload BDF fonts
      uses: actions/upload-artifact@v4
      with: 
        name: bdf-fonts
        path: bdf-fonts
