name: Binaries CI

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
     
    - name: make bfs binary
      run:  make bfs-bin
      
    - name: make me binary
      run: |
        sudo apt install gcc-mingw-w64-i686 mingw-w64-tools
        make me-bin
        make mingw-w32-compile

    - name: make me-standalone binary
      run: make me-bfs-bin
    
    - name: Make me-standalone binary
      run: |
        mkdir binaries-Linux-x86_64
        mkdir binaries-Windows-32
        cp bfs/bfs binaries-Linux-x86_64/
        cp me-linux.bin binaries-Linux-x86_64/me-linux.bin
        cp license.txt binaries-Linux-x86_64/
        cp README-standalone.md binaries-Linux-x86_64/
        cp me-windows.exe binaries-Windows-32/
        cp mec-windows.exe binaries-Windows-32/
        cp bin/bfs.exe binaries-Windows-32/
        cp license.txt binaries-Windows-32/
        cp README-standalone.md binaries-Windows-32/
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v3
      with: 
        name: binaries-Linux-x86_64
        path: binaries-Linux-x86_64
    - name: Upload Artifact GitHub Action Windows
      uses: actions/upload-artifact@v3
      with: 
        name: binaries-Windows-32
        path: binaries-Windows-32
