name: MacOS-11

on:
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies on MacOS and compile and produce BFS exes and standalone ME application 
        if: runner.os == 'macOS'
        run: |
           echo `uname -a`
           ls
           
