name: Binaries CI

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
     
    - name: make bfs binary
      run: make bfs-bin
      
    - name: make me binary
      run: make me-bin

    - name: make me-standalone binary
      run: make me-bfs-bin
    
    - name: Make me-standalone binary
      run: |
        mkdir binaries
        cp src/me binaries/
        cp bfs/bfs binaries/
        cp me-linux.bin binaries/me-linux-x64.bin
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: binaries
        path: binaries
