name: Binaries Ubuntu 20 (linux-gcc)

on:
  workflow_dispatch:
    branches: [ master ]
env:
   VERSION: "091224b1"
jobs:
  build:
    runs-on: ubuntu-20.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v4
     
    - name: developer library installs
      run: |
        sudo apt install build-essential
        sudo apt install desktop-file-utils

    - name: make bfs binary
      run:  make -f linux32gcc.gmk bfs/bin

    - name: make mec binary       
      run:  make -f linux32gcc.gmk mec

    - name: make mew binary       
      run:  make -f linux32gcc.gmk mew

    - name: make mecw binary       
      run:  make -f linux32gcc.gmk mecw

    - name: make mecb binary
      run:  |
        make -f linux32gcc.gmk mecb
    
    - name: make mewb binary
      run:  make -f linux32gcc.gmk mewb
    
    - name: make mecwb binary
      run:  make -f linux32gcc.gmk mecwb
    
    - name: Make release
      run: |
        mkdir MicroEmacs09-${VERSION}-Linux
        mkdir MicroEmacs09-${VERSION}-Linux/bin
        mkdir -p MicroEmacs09-${VERSION}-Linux/man/1   
        mkdir -p MicroEmacs09-${VERSION}-Linux/share/jasspa
        mkdir MicroEmacs09-${VERSION}-Linux/share/spelling
        mkdir MicroEmacs09-${VERSION}-Linux/share/company        
        cp doc/me.1 MicroEmacs09-${VERSION}-Linux/man/1/
        cp bfs/bfs MicroEmacs09-${VERSION}-Linux/bin/
        cp src/.linux32gcc-release-mecw/mecw MicroEmacs09-${VERSION}-Linux/bin/
        cp src/.linux32gcc-release-mew/mew MicroEmacs09-${VERSION}-Linux/bin/
        cp src/.linux32gcc-release-mec/mec  MicroEmacs09-${VERSION}-Linux/bin/
        cp me*.bin MicroEmacs09-${VERSION}-Linux/bin/
        cp license.txt MicroEmacs09-${VERSION}-Linux/share/jasspa/
        cp COPYING MicroEmacs09-${VERSION}-Linux/share/jasspa/
        cp README-standalone.md MicroEmacs09-${VERSION}-Linux/share/jasspa/
        cp jasspa/macros MicroEmacs09-${VERSION}-Linux/share/jasspa/
        cp jasspa/macros.zip MicroEmacs09-${VERSION}-Linux/
        echo "Documentation is in share/jasspa" > MicroEmacs09-${VERSION}-Linux/readme.txt
        zip macros-${VERSION}.zip jasspa/macros/*

    - name: Make mecb release
      run: |
        mkdir MicroEmacs09-${VERSION}-Linux-mecb
        mkdir MicroEmacs09-${VERSION}-Linux-mecb/bin
        cp bfs/bfs MicroEmacs09-${VERSION}-Linux-mecb/bin/
        cp mecb*.bin MicroEmacs09-${VERSION}-Linux-mecb/bin/
        cp license.txt MicroEmacs09-${VERSION}-Linux-mecb/
        cp COPYING MicroEmacs09-${VERSION}-Linux-mecb/
        cp README-standalone.md MicroEmacs09-${VERSION}-Linux-mecb/

    - name: Make mewb release
      run: |
        mkdir MicroEmacs09-${VERSION}-Linux-mewb
        mkdir MicroEmacs09-${VERSION}-Linux-mewb/bin
        cp bfs/bfs MicroEmacs09-${VERSION}-Linux-mewb/bin/
        cp mewb*.bin MicroEmacs09-${VERSION}-Linux-mewb/bin/
        cp license.txt MicroEmacs09-${VERSION}-Linux-mewb/
        cp COPYING MicroEmacs09-${VERSION}-Linux-mewb/
        cp README-standalone.md MicroEmacs09-${VERSION}-Linux-mewb/

    - name: Make mecwb release
      run: |
        mkdir MicroEmacs09-${VERSION}-Linux-mecwb
        mkdir MicroEmacs09-${VERSION}-Linux-mecwb/bin
        cp bfs/bfs MicroEmacs09-${VERSION}-Linux-mecwb/bin/
        cp mecwb*.bin MicroEmacs09-${VERSION}-Linux-mecwb/bin/
        cp license.txt MicroEmacs09-${VERSION}-Linux-mecwb/
        cp COPYING MicroEmacs09-${VERSION}-Linux-mecwb/
        cp README-standalone.md MicroEmacs09-${VERSION}-Linux-mecwb/

    - name: Upload Ubuntu Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VERSION }}-Linux
        path: MicroEmacs09-${{ env.VERSION }}-Linux
    
    - name: Upload Ubuntu mecb Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VERSION }}-Linux-mecb
        path: MicroEmacs09-${{ env.VERSION }}-Linux-mecb

    - name: Upload Ubuntu mewb Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VERSION }}-Linux-mewb
        path: MicroEmacs09-${{ env.VERSION }}-Linux-mewb

    - name: Upload Ubuntu mecwb Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VERSION }}-Linux-mecwb
        path: MicroEmacs09-${{ env.VERSION }}-Linux-mecwb

    - name: Jasspa Macros
      uses: actions/upload-artifact@v4
      with:
        name: macros-${{ env.VERSION }}
        path: macros-${{ env.VERSION }}.zip     
