name: MacOS-11

on:
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies on MacOS and compile and produce BFS exes and standalone ME application 
        if: runner.os == 'macOS'
        run: |
           echo `uname -a`
           ls
           brew install xquartz
           brew install gcc
           brew install make
           cd bfs && /usr/local/opt/make/libexec/gnubin/make CC=gcc-10
           cd ../src && /usr/local/opt/make/libexec/gnubin/make -f macos32gcc.gmk  CC=gcc-10
           cd ../src && /usr/local/opt/make/libexec/gnubin/make -f macos32gcc.gmk  CC=gcc-10 BTYP=c
           cd ..
           mkdir binaries-MacOS-11
           cp src/.macos32gcc-release-mecw/mecw binaries-MacOS-11/
           cp src/.macos32gcc-release-mec/mec binaries-MacOS-11/           
           tar cfvz jasspa.tar.gz jasspa/*
           cp jasspa.tar.gz binaries-MacOS-11/
           rm -rf jasspa/company
           rm -rf jasspa/pixmaps
           rm -rf jasspa/contrib           
           ./bfs/bfs -a src/.macos32gcc-release-mecw/mecw -o binaries-MacOS-11/mecw-macos.bin ./jasspa
           ./bfs/bfs -a src/.macos32gcc-release-mec/mec   -o binaries-MacOS-11/mec-macos.bin ./jasspa           
           cp bfs/bfs binaries-MacOS-11/
           chmod 755 ./me-macos.bin 
           ./me-macos.bin -n -V
           cp README-standalone.md binaries-MacOS-11/
           cp faq.txt license.txt binaries-MacOS-11/
           echo '-1 ml-write &cat "Platform:" $platform' > platform.emf
           echo "exit-emacs" >> platform.emf
           TERM=xterm ./me-macos.bin @platform.emf
      - name: Upload Artifact GitHub Action
        uses: actions/upload-artifact@v3
        with: 
           name: binaries-MacOS-11
           path: binaries-MacOS-11
           
