name: MacOS-11

on:
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies on MacOS and compile and produce BFS exes and standalone ME application 
        if: runner.os == 'macOS'
        run: |
           echo `uname -a`
           ls
           brew install xquartz
           brew install gcc
           brew install make
           cd bfs && /usr/local/opt/make/libexec/gnubin/make
           cd ../src && /usr/local/opt/make/libexec/gnubin/make -f macos32gcc.gmk 
           cd ..
           mkdir binaries-MacOS
           cp src/.macos32gcc-release-mecw/mecw binaries-MacOS/
           tar cfvz jasspa.tar.gz jasspa/*
           
