name: MacOS

on:
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.1.1']

    steps:
      - uses: actions/checkout@v3
      - name: Install X11 dependencies on MacOS  
        if: runner.os == 'macOS'
        run: |
           brew install xquartz
           brew install gcc
           brew install make
           cd src && /usr/local/opt/make/libexec/gnubin/make -f macos32gcc.gmk 
