name: Binaries Ubuntu 22 (linux32gcc)

on:
  workflow_dispatch:
    branches: [ master ]
env:
   VERSION: "091224b"
   OS: "ubuntu-22"
jobs:
  build:
    runs-on: ubuntu-22.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v4
     
    - name: developer library installs
      run: |
        sudo apt install build-essential
        sudo apt install desktop-file-utils

    - name: make bfs binary
      run:  make -f linux32gcc.gmk bfs/bin

    - name: make mec binary       
      run:  make -f linux32gcc.gmk mec

    - name: make mew binary       
      run:  make -f linux32gcc.gmk mew

    - name: make mecb binary
      run:  |
        make -f linux32gcc.gmk mecb
    
    - name: make mewb binary
      run:  make -f linux32gcc.gmk mewb
    
    - name: Make release
      run: |
        mkdir MicroEmacs09-${VERSION}-${OS}
        mkdir MicroEmacs09-${VERSION}-${OS}/bin
        cp bfs/bfs MicroEmacs09-${VERSION}-${OS}/bin/
        cp src/.${OS}32gcc-release-mecw/mecw MicroEmacs09-${VERSION}-${OS}/bin/
        cp src/.${OS}32gcc-release-mec/mec  MicroEmacs09-${VERSION}-${OS}/bin/
        cp me*.bin MicroEmacs09-${VERSION}-${OS}/bin/
        cp license.txt MicroEmacs09-${VERSION}-${OS}/
        cp COPYING MicroEmacs09-${VERSION}-${OS}/
        cp README-standalone.md MicroEmacs09-${VERSION}-${OS}/
        cd jasspa 
        zip macros.zip macros/*
        cd ..
        cp jasspa/macros.zip MicroEmacs09-${VERSION}-${OS}/

    - name: Make mecb release
      run: |
        mkdir MicroEmacs09-${VERSION}-${OS}-mecb
        mkdir MicroEmacs09-${VERSION}-${OS}-mecb/bin
        cp bfs/bfs MicroEmacs09-${VERSION}-${OS}-mecb/bin/
        cp mec*.bin MicroEmacs09-${VERSION}-${OS}-mecb/bin/
        cp license.txt MicroEmacs09-${VERSION}-${OS}-mecb/
        cp COPYING MicroEmacs09-${VERSION}-${OS}-mecb/
        cp README-standalone.md MicroEmacs09-${VERSION}-${OS}-mecb/

    - name: Make mewb release
      run: |
        mkdir MicroEmacs09-${VERSION}-${OS}-mewb
        mkdir MicroEmacs09-${VERSION}-${OS}-mewb/bin
        cp bfs/bfs MicroEmacs09-${VERSION}-${OS}-mewb/bin/
        cp mew*.bin MicroEmacs09-${VERSION}-${OS}-mewb/bin/
        cp license.txt MicroEmacs09-${VERSION}-${OS}-mewb/
        cp COPYING MicroEmacs09-${VERSION}-${OS}-mewb/
        cp README-standalone.md MicroEmacs09-${VERSION}-${OS}-mewb/

    - name: Upload Ubuntu Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}
        path: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}
    
    - name: Upload Ubuntu mecb Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}-mecb
        path: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}-mecb

    - name: Upload Ubuntu mewb Release files
      uses: actions/upload-artifact@v4
      with: 
        name: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}-mewb
        path: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}-mewb
