name: Binaries MacOS-12 (macos32gcc)

on:
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies on MacOS and compile and produce BFS exes and standalone ME application 
        run: |
           echo `uname -a`
           cat /etc/os-*
           ls
           brew install xquartz
           brew install gcc
           brew install make

      - name: make bfs binary
        run: make -f macos32gcc.gmk bfs/bin CC=gcc-11   

      - name: make mec binary
        run:  make -f macos32gcc.gmk mec

      - name: make mew binary
        run: make -f macos32gcc.gmk mew
        
      - name: make mecb binary 
        run: make -f macos32gcc.gmk mecb
        
      - name: make mewb binary 
        run: make -f macos32gcc.gmk mewb
        
