name: Binaries CI

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v2
     
    - name: make bfs binary
      run: make bfs-bin
      
    - name: make me binary
      run: make me-bin

    - name: make me-standalone binary
      run: make me-bfs-bin
    
    - name: Make me-standalone binary
      run: |
        mkdir binaries-Linux-x86_64
        cp bfs/bfs binaries-Linux-x86_64/
        cp me-linux.bin binaries-Linux-x86_64/me-linux.bin
        cp license.txt binaries-Linux-x86_64/
        cp README-standalone.md binaries-Linux-x86_64/        
    - name: Upload Artifact GitHub Action
      uses: actions/upload-artifact@v2
      with: 
        name: binaries-Linux-x86_64
        path: binaries-Linux-x86_64
