name: Binaries MacOS-13 (macos32gcc)

on:
  workflow_dispatch:
    branches: [ master ]

permissions:
  contents: read
env:
   VERSION: "091224b1"
   OS: "macos-13"
jobs:
  build:
    runs-on: macos-13
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies on MacOS and compile and produce BFS exes and standalone ME application 
        run: |
           echo `uname -a`
           uname -r
           brew install xquartz
           brew install make
           export PATH=/usr/local/opt/make/libexec/gnubin/:PATH
           export VRS=`grep -E 'meYEAR|meMONTH|meDAY' src/evers.h | head -n 3 | awk '{ print $3 }' | sed 's/"//'g | paste -sd ''`

      - name: make bfs binary
        run: make -f macos32gcc.gmk bfs/bin CC=gcc-13   

      - name: make mec binary
        run:  make -f macos32gcc.gmk mec CC=gcc-13

      - name: make mew binary
        run: make -f macos32gcc.gmk mew CC=gcc-13
        
      - name: make mecw binary
        run: make -f macos32gcc.gmk mecw CC=gcc-13
        
      - name: make mecb binary 
        run: make -f macos32gcc.gmk mecb 
        
      - name: make mewb binary 
        run: make -f macos32gcc.gmk mewb
        
      - name: make mecwb binary 
        run: make -f macos32gcc.gmk mecwb
        
      - name: Make release
        run: |
          mkdir MicroEmacs09-${VERSION}-${OS}
          mkdir MicroEmacs09-${VERSION}-${OS}/bin
          cp bfs/bfs MicroEmacs09-${VERSION}-${OS}/bin/
          cp src/.macos32gcc-release-mecw/mecw MicroEmacs09-${VERSION}-${OS}/bin/
          cp src/.macos32gcc-release-mec/mec  MicroEmacs09-${VERSION}-${OS}/bin/
          cp src/.macos32gcc-release-mew/mew  MicroEmacs09-${VERSION}-${OS}/bin/          
          cp me*.bin MicroEmacs09-${VERSION}-${OS}/bin/
          cp license.txt MicroEmacs09-${VERSION}-${OS}/
          cp COPYING MicroEmacs09-${VERSION}-${OS}/
          cp README-standalone.md MicroEmacs09-${VERSION}-${OS}/
          cd jasspa 
          zip macros.zip macros/*
          cd ..
          cp jasspa/macros.zip MicroEmacs09-${VERSION}-${OS}/

      - name: Make mecb release
        run: |
          mkdir MicroEmacs09-${VERSION}-${OS}-mecb
          mkdir MicroEmacs09-${VERSION}-${OS}-mecb/bin
          cp bfs/bfs MicroEmacs09-${VERSION}-${OS}-mecb/bin/
          cp mecb*.bin MicroEmacs09-${VERSION}-${OS}-mecb/bin/
          cp license.txt MicroEmacs09-${VERSION}-${OS}-mecb/
          cp COPYING MicroEmacs09-${VERSION}-${OS}-mecb/
          cp README-standalone.md MicroEmacs09-${VERSION}-${OS}-mecb/

      - name: Make mewb release
        run: |
          mkdir MicroEmacs09-${VERSION}-${OS}-mewb
          mkdir MicroEmacs09-${VERSION}-${OS}-mewb/bin
          cp bfs/bfs MicroEmacs09-${VERSION}-${OS}-mewb/bin/
          cp mewb*.bin MicroEmacs09-${VERSION}-${OS}-mewb/bin/
          cp license.txt MicroEmacs09-${VERSION}-${OS}-mewb/
          cp COPYING MicroEmacs09-${VERSION}-${OS}-mewb/
          cp README-standalone.md MicroEmacs09-${VERSION}-${OS}-mewb/

      - name: Make mecwb release
        run: |
          mkdir MicroEmacs09-${VERSION}-${OS}-mecwb
          mkdir MicroEmacs09-${VERSION}-${OS}-mecwb/bin
          cp bfs/bfs MicroEmacs09-${VERSION}-${OS}-mecwb/bin/
          cp mecwb*.bin MicroEmacs09-${VERSION}-${OS}-mecwb/bin/
          cp license.txt MicroEmacs09-${VERSION}-${OS}-mecwb/
          cp COPYING MicroEmacs09-${VERSION}-${OS}-mecwb/
          cp README-standalone.md MicroEmacs09-${VERSION}-${OS}-mecwb/

      - name: Upload MacOS-13 Release files
        uses: actions/upload-artifact@v4
        with: 
          name: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}
          path: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}
    
      - name: Upload Ubuntu mecb Release files
        uses: actions/upload-artifact@v4
        with: 
          name: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}-mecb
          path: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}-mecb

      - name: Upload Ubuntu mewb Release files
        uses: actions/upload-artifact@v4
        with: 
          name: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}-mewb
          path: MicroEmacs09-${{ env.VERSION }}-${{ env.OS }}-mewb

      - name: Upload Ubuntu mecwb-2 Release files
        uses: actions/upload-artifact@v4
        with: 
          name: MicroEmacs09-${{ env.VRS }}-${{ env.OS }}-mecwb
          path: MicroEmacs09-${{ env.VRS }}-${{ env.OS }}-mecwb
