name: Cygwin Workflow

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: bash git make gcc-core gcc-g++
        install-dir: C:\cygwin
        
    - name: Modify PATH
      run: |
        echo "C:\cygwin\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Verify Cygwin installation
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        echo $PATH
        which bash
        bash --version

    - name: Run your commands
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        # Your Cygwin commands here
        cygcheck -c
        make --version
        gcc --version
        

    - name: Verify Python Installation
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        python3 --version
        which python3
    - name: Install MicroEmacs
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        echo $PATH
        which pip
        pip install https://github.com/user-attachments/files/16837822/meapp-9.12.24b1.tar.gz --user
        meapp -V
