name: Cygwin Workflow

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Install Cygwin
      uses: egor-tensin/setup-cygwin@v4
      with:
        packages: bash git make gcc-core gcc-g++ python3-pip wget zlib-devel libncurses-devel libXft-devel
        install-dir: C:\cygwin
        
    - name: Modify PATH
      run: |
        echo "C:\cygwin\bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
        
    - name: Verify Cygwin installation
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        echo $PATH
        which bash
        bash --version

    - name: Run your commands
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        # Your Cygwin commands here
        cygcheck -c
        make --version
        gcc --version
        
    - name: Install apt-cyg
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        wget https://raw.githubusercontent.com/transcode-open/apt-cyg/master/apt-cyg
        install apt-cyg /bin
        chmod +x /bin/apt-cyg
        apt-cyg install nano
        
    - name: Verify Python Installation
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        python3 --version
        which python3

    - name: Clone MicroEmacs
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        mkdir workspace
        cd workspace
        git clone https://github.com/mittelmark/microemacs.git
        cd microemacs
        make -f cygwin.gmk mec mecb
        make -f cygwin.gmk mew mewb        
        
    - name: Install MicroEmacs
      shell: C:\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
      run: |
        echo $PATH
        which pip3
        pip3 install https://github.com/user-attachments/files/16839413/meapp-9.12.24b1.tar.gz
        export PATH=~/.local/bin:$PATH
        cat /etc/os-release
        meapp -V
