name: Testing Action features

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Build on Ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check Python package install
        run:  |
          uname -a
          uname -n
          uname -s
          python --version
          python -m venv menv
          ./menv/bin/pip install https://github.com/user-attachments/files/16837822/meapp-9.12.24b1.tar.gz
          ./menv/bin/meapp -V
  macos:
    runs-on: macos-latest
    name: Build on MacOS latest
    steps:
      - uses: actions/checkout@v4
      - name: check Python package install
        run:  |
          uname -a
          uname -n
          uname -s
          python --version
          python -m venv menv
          ./menv/bin/pip install https://github.com/user-attachments/files/16837822/meapp-9.12.24b1.tar.gz
          ./menv/bin/meapp -V

  windows:
    runs-on: windows-2022
    name: Build on Windows 2022

    steps:
      - uses: actions/checkout@v4
      - name: check Python package install
        run:  |
          python --version
          python -c "import sys; print(sys.executable)"
          pip --version
          #pip install https://github.com/user-attachments/files/16837822/meapp-9.12.24b1.tar.gz
          python -m venv menv
          dir menv\Scripts
          menv\Scripts\activate.bat
          $Env:PATH = [System.Environment]::CurrentDirectory + "menv\Scripts" + ";"+$Env:PATH
          python -c "import sys; print(sys.executable)"
          pip install https://github.com/user-attachments/files/16837822/meapp-9.12.24b1.tar.gz --user
          dir /b /s /AD menv
          
          $Env:PATH += ";C:\Users\runneradmin\AppData\Roaming\Python\Python39\Scripts"
          dir /b /s /AD C:\Users\runneradmin\AppData\Roaming\Python\Python39

          dir C:\Users\runneradmin\AppData\Roaming\Python\Python39\Scripts
          dir C:\Users\runneradmin\AppData\Roaming\Python\Python39\site-packages\meapp\jasspa
          #dir menv
          #dir menv\lib
          #dir menv\lib\site-packages
          #dir menv\Scripts
          #dir C:\hostedtoolcache\windows\Python\3.9.13\x64          
          #dir C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\meapp\jasspa
          meapp -V
          #meapp -V  
          ## venv seems not to work
