name: Testing Action features

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4
      - name: check cygwin install
        run:  |
          uname -a
          uname -n
          uname -s
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: check uname mac-os-14
        run:  |
          uname -a
          uname -n
          uname -s
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: check chck the path
        shell: cmd
        run:  |
          echo %PATH%
      - name: Set up Cygwin
        uses: egor-tensin/setup-cygwin@v4
        with:
          packages: cmake gcc-g++
        
        # Cygwin executables are added to PATH, so you can call them directly:
        run: |
           ls.exe -Al
           pwd.exe
        
        # Alternatively, you can set Cygwin's bash as the shell to use:
        run: |
           # This is a real bash script!
           basic() {
               ls -Al
               pwd
           }
           basic
           shell: C:\tools\cygwin\bin\bash.exe --login --norc -eo pipefail -o igncr '{0}'
                                          
    
