name: Testing Action features

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Build on Ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check Python package install
        run:  |
          uname -a
          uname -n
          uname -s
          python --version
          python -m venv menv
          ./menv/bin/pip install https://github.com/user-attachments/files/16840928/meapp-9.12.24b1.tar.gz
          ./menv/bin/meapp -V
  macos:
    runs-on: macos-latest
    name: Build on MacOS latest
    steps:
      - uses: actions/checkout@v4
      - name: check Python package install
        run:  |
          uname -a
          uname -n
          uname -s
          python --version
          python -m venv menv
          ./menv/bin/pip install https://github.com/user-attachments/files/16840928/meapp-9.12.24b1.tar.gz
          ./menv/bin/meapp -V

  macos13:
    runs-on: macos-13
    name: Build on MacOS 13
    steps:
      - uses: actions/checkout@v4
      - name: check MicroEmacs curl install
        shell: bash
        run:  |
          brew install xquartz
          curl -fsSL https://raw.githubusercontent.com/mittelmark/microemacs/refs/heads/master/install-linux.sh  -o install.sh
          bash install.sh -V
          source ~/.bashrc ## for the current session
          me -V

  windows:
    runs-on: windows-2022
    name: Build on Windows 2022

    steps:
      - uses: actions/checkout@v4
      - name: check Python package install
        run:  |
          python --version
          python -c "import sys; print(sys.executable)"
          pip --version
          #pip install https://github.com/user-attachments/files/16840928/meapp-9.12.24b1.tar.gz
          python -m venv menv
          dir menv\Scripts
          menv\Scripts\activate.bat
          $Env:PATH = [System.Environment]::CurrentDirectory + "menv\Scripts" + ";"+$Env:PATH
          python -c "import sys; print(sys.executable)"
          python -c "import os; print(os.path.expanduser('~'))"
          pip install https://github.com/user-attachments/files/16840928/meapp-9.12.24b1.tar.gz
          $Env:PATH += ";C:\Users\runneradmin\AppData\Roaming\Python\Python39\Scripts"
          meapp -V 
