name: Testing Action features

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Build on Ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: check Python package install
        run:  |
          uname -a
          uname -n
          uname -s
          python --version
          python -m venv menv
          ./menv/bin/pip install https://github.com/user-attachments/files/16836407/meapp-9.12.24b1.tar.gz
          ./menv/bin/meapp -V
  macos:
    runs-on: macos-latest
    name: Build on MacOS latest
    steps:
      - uses: actions/checkout@v4
      - name: check Python package install
        run:  |
          uname -a
          uname -n
          uname -s
          python --version
          python -m venv menv
          ./menv/bin/pip install https://github.com/user-attachments/files/16836407/meapp-9.12.24b1.tar.gz
          ./menv/bin/meapp -V

  windows:
    runs-on: windows-2019
    name: Build on Windows 2019

    steps:
      - uses: actions/checkout@v4
      - name: check Python package install
        run:  |
          python --version
          pip --version
          pip install https://github.com/user-attachments/files/16836407/meapp-9.12.24b1.tar.gz
          meapp -V  
          ## venv seems not to work
