name: Testing Action features

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4
      - name: check cygwin install
        run:  |
          uname -a
          uname -n
          uname -s
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: check uname mac-os-14
        run:  |
          uname -a
          uname -n
          uname -s
  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: check chck the path
        shell: cmd
        run:  |
          echo %PATH%
        
    
