name: Test Binaries on Windows Server

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-2019
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
    - uses: actions/checkout@v3
     
    - name: download winlibs
      shell: cmd
      run: |
        curl -OL https://github.com/brechtsanders/winlibs_mingw/releases/download/12.2.0-16.0.0-10.0.0-ucrt-r5/winlibs-i686-posix-dwarf-gcc-12.2.0-mingw-w64ucrt-10.0.0-r5.zip
        unzip -q winlibs-i686-posix-dwarf-gcc-12.2.0-mingw-w64ucrt-10.0.0-r5.zip
        PATH=%CD%\mingw32\bin;%PATH%
        gcc --version
    - name: compile zlib
      shell: cmd
      run: |
        cd 3rdparty/zlib 
        mingw32-make -f win32mingw.mak
        ls .win32mingw-release\*
        copy .win32mingw-release\zlib.a ..\..\mingw32\lib\libz.a
        cd ../../
    - name: compile bfs
      shell:  cmd
      run: |
        cd bfs
        mingw32-make -f Makefile.mingw RC=windres STRIP=strip
        ls
        cd ..
    - name: compile mecw
      shell: cmd
      run: |
        cd src
        mingw32-make -f win32mingw.mak RC=windres STRIP=strip
        ls 
        ls .win32mingw-release-mecw
        

        
        
    
