name: Test-Workflow

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      OSL: ubuntu-20-x86_64
      OSW: windows-32
    steps:
    - uses: actions/checkout@v3
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! OSL=$OSL OSW=$OSW"
        env:
          First_Name: Mona
      - name: "Say Hello Mona it's Monday 2"
        run: echo "$Greeting $First_Name again. Today is $DAY_OF_WEEK!"
        env:
          First_Name: Mona
      - name: make bfs binary
        run:  make bfs-bin
      - name: Make me-standalone binary
        run: |
          mkdir "$OSL"
          mkdir "$OSW"
          ls 
