name: Testing Action features

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  linux:
    runs-on: ubuntu-latest
    name: Build on ${{ matrix.distro }} ${{ matrix.arch }}

    steps:
      - uses: actions/checkout@v4
      - name: check cygwin install
        run:  |
          uname -a
          uname -n
          uname -s
  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: check uname mac-os-14
        run:  |
          uname -a
          uname -n
          uname -s
          python --version
          python -m venv menv
          ./menv/bin/pip install https://github.com/user-attachments/files/16836036/meapp-9.12.24b1.tar.gz
          ./menv/bin/meapp -V
